#!/bin/bash
wallpaper="$(find /etc/greetd/wallpaper -maxdepth 1 -type f | shuf -n 1)"

new_css="window {
    background-image: url('file://$wallpaper');
    background-size: cover;
    background-position: center;
    background-color: rgba(100, 0, 0, 0.6);
}
window :not(box) box {
    background-color: rgba(100, 0, 0, 0.6);
}
"

echo "$new_css" > /etc/greetd/gtkgreet.css
echo "done"
